### ISSUE TITLE
😠

### ISSUE THREAD

**Issue by ShrkSoft** [charllote12/myLog#4]
クソ忙しい中でいつ来るのかな〜って思ってたのに来なかった-1145141919810点
風邪だもんね、しょうがないね
狐はもう3色しかありません。着払いで送りつけましょうか？
あと近いうちにもうちょっと大きいサイズのが入りそうです。いつかは知らんけど

**Comment by charllote12** [comment]
うわーーーーごめんよぉーーー!!!!!

狐送り付けられてくるってマジ???そんなことがあっっていいのかい???

次行けるとしたら来週16-20の間、仕事に余裕があれば。
あとは来年１月下旬、２月上旬、３月中旬、4月以降も

**Comment by ShrkSoft** [comment]
17から19日ならいるで
ただ18と19に来るなら16時以降じゃないといない

**Comment by charllote12** [comment]
行くなら仕事終わりなので、それくらいになるのかな...?

**Comment by ShrkSoft** [comment]
来店待ってます
