### ISSUE TITLE
気にするな

### ISSUE THREAD

**Issue by ShrkSoft** [charllote12/myLog#5]
ホームページも閲覧数伸びないし、ツイートした所で何も起きないし、mixi2のインプレッション数他の人は300とか超えてるのに自分は15というクソ数だし、コスプレした所で鏡を見ればブスな自分が写ってるし、鯖作れば過疎だし
そういう普通に萎えるの自分も経験してる
ゲームでいうスキルポイントの割り振りを全部仕事に回してるって考えれば、多少は楽になるんじゃない？

**Comment by ShrkSoft** [comment]
おすすめはこちら
[これ](https://www.youtube.com/watch?v=MXfYuRi-fWk)
[FC音源版は責任とらなくていいらしい](https://www.youtube.com/watch?v=awd4fXcXO4E)

**Comment by charllote12** [comment]
ふぁっ、今気づいたぞ。
あじゃどうやで。

また来月以降で現地休暇あれば今度こそお邪魔するぜ
